//! Std-free error functions `erf`/`erfc` for `f32` and `f64`, with a
//! numerical-correctness guarantee verified by tests.
//!
//! `f32::erf`/`f64::erf` are not available in `no_std` (and still unstable
//! in std — rust-lang `float_erf`), so this module provides portable
//! replacements. Clean-room implementation: the piecewise structure follows
//! the publicly documented fdlibm method (region boundaries, the
//! `z`-trick for the tail, split small-region forms to avoid cancellation),
//! but every coefficient below was freshly fitted with a Remez exchange
//! algorithm against an arbitrary-precision (mpmath, 80 digits) oracle.
//! No code or constants were copied from C libraries.
//!
//! Accuracy (enforced by tests against the mpmath oracle table in
//! `erf_reference.rs`, generated by `scripts/gen_erf_reference.py`):
#![allow(
    clippy::cast_possible_truncation, // f64 → f32 final rounding is the f32 contract
    clippy::cast_possible_wrap, // bit-pattern casts in test ulp helpers
    clippy::cast_sign_loss // u32 → i64 bit-pattern casts in test ulp helpers
)]
//! * `erf_f64`: ≤ 1 ulp over the whole domain.
//! * `erfc_f64`: ≤ 3 ulp over the whole domain. The tail
//!   `erfc(x) = exp(−z²−0.5625)·exp((z−x)(z+x)+L(1/x²))/x` is a product of
//!   two rounded exponentials, so ≤ 3 ulp is the structural floor of this
//!   form (musl/fdlibm share it); a single-exp tail cannot represent the
//!   subnormal range `x ∈ [26.5, 27.23]` at all.
//! * `erf`/`erfc` (f32): computed in f64 and rounded once — perfectly
//!   rounded (0 ulp measured over all 891,117 non-negative f32 inputs;
//!   f32-native arithmetic cancels catastrophically in every region).
//!
//! Regions (|x|): `[0, 2^-56)` tiny; `[2^-56, 0.25)` and `[0.25, 0.84375)`
//! small (R-form); `[0.84375, 1.25)` middle (rational in s = |x|−1);
//! `[1.25, 27.23]` tail (z-trick); beyond → saturation.

#![allow(
    clippy::excessive_precision, // Remez coefficients are full-precision by design
    clippy::many_single_char_names,
    clippy::float_cmp, // exact-value asserts on the oracle table are intentional
)]

/// |x| < 0.84375: erf(x) = x + x·R(x²) region (fdlibm boundary: the fixed
/// point of erf is near 0.6174; 0.84375 keeps the form ≤ 1 ulp).
pub(crate) const T_SMALL: f64 = 0.84375;
/// |x| < 1.25: middle region, rational in s = |x| − 1.
pub(crate) const T_MID: f64 = 1.25;
/// Tail split: 1/0.35 ≈ 2.857 (boundary between the two L fits).
pub(crate) const T_SPLIT: f64 = 1.0 / 0.35;
/// erfc(27.23) ≈ 5e-324 (smallest subnormal); beyond this erfc = 0, erf = ±1.
pub(crate) const XMAX: f64 = 27.23;
/// 2^-56: below this, `erfc(x) = 1 − x` is correctly rounded (the cubic
/// term of the series is < ½ ulp of 1).
pub(crate) const T_TINY: f64 = 1.387_778_780_781_445_7e-17;

/// R(t) ≈ (erf(x)−x)/x, t = x², on [0, 0.84375²]. Remez fit, ascending
/// powers; R(0) = 2/√π − 1 so `x + x·R(x²)` is exact at 0. Fit error
/// 2.05e-23 (75 bits).
pub(crate) const ERF_R: [f64; 14] = [
    1.283_791_670_955_125_9e-1,
    -3.761_263_890_318_375_4e-1,
    1.128_379_167_095_512_6e-1,
    -2.686_617_064_513_121_4e-2,
    5.223_977_625_441_483e-3,
    -8.548_327_023_371_254e-4,
    1.205_533_297_596_852e-4,
    -1.492_565_006_925_313_4e-5,
    1.646_210_434_547_912_8e-6,
    -1.636_559_962_560_406_5e-7,
    1.480_297_398_588_027_2e-8,
    -1.224_039_301_727_522_7e-9,
    9.028_138_024_043_73e-11,
    -4.829_561_243_697_735e-12,
];

/// erfc(1+s) ≈ P(s)/Q(s), s ∈ [−0.15625, 0.25). Remez fit, ascending
/// powers; Q(0) = 1. Fit error 1.9e-28 (92 bits).
pub(crate) const ERFC1_NUM: [f64; 10] = [
    1.572_992_070_502_851_3e-1,
    -3.579_521_284_198_039e-1,
    3.374_729_044_798_999e-1,
    -1.629_448_334_465_087e-1,
    3.935_497_348_186_852e-2,
    -4.911_980_978_193_859e-3,
    2.424_117_060_668_996_4e-3,
    -1.626_331_315_358_599e-3,
    4.601_058_710_808_035e-4,
    -4.856_542_938_472_312_4e-5,
];
pub(crate) const ERFC1_DEN: [f64; 10] = [
    1.0,
    3.633_544_635_893_777_3e-1,
    4.653_333_636_519_545_5e-1,
    1.128_838_389_462_511e-1,
    7.954_375_912_843_319e-2,
    1.010_834_963_105_127_5e-2,
    5.647_032_996_787_97e-3,
    -1.608_851_321_107_024_4e-4,
    1.082_224_773_875_178_4e-4,
    -4.853_500_977_282_621_4e-5,
];

/// L(u) ≈ ln(x·eˣ²·erfc(x)) + 0.5625, u = 1/x², x ∈ [1.25, 1/0.35).
/// Remez rat(10,10), ascending powers; fit error 74 bits.
pub(crate) const LA_NUM: [f64; 11] = [
    -9.864_942_946_068_79e-3,
    -7.955_172_079_182_581e-1,
    -1.777_644_002_558_133_4e1,
    -1.762_326_065_058_628_6e2,
    -8.959_130_956_027_066e2,
    -2.449_963_863_444_432_7e3,
    -3.596_656_104_061_51e3,
    -2.715_958_274_978_995e3,
    -9.595_302_027_820_248e2,
    -1.307_955_064_574_635_7e2,
    -4.283_829_406_560_128,
];
pub(crate) const LA_DEN: [f64; 11] = [
    1.0,
    2.995_630_209_606_2e1,
    3.470_155_740_862_721_3e2,
    2.017_837_044_533_574_3e3,
    6.407_754_355_989_598e3,
    1.135_111_526_685_298_7e4,
    1.102_114_887_652_878_9e4,
    5.547_083_120_150_904e3,
    1.295_003_894_675_540_1e3,
    1.120_875_254_040_922_8e2,
    2.025_906_237_065_879,
];

/// Same L, x ∈ [1/0.35, 27.23]. Remez rat(11,10), ascending powers;
/// fit error 84 bits.
pub(crate) const LB_NUM: [f64; 12] = [
    -9.864_942_924_700_087e-3,
    -1.177_108_459_288_053_6,
    -5.252_856_863_854_7e1,
    -1.190_012_213_949_467e3,
    -1.528_236_599_675_582_7e4,
    -1.159_381_302_508_472_7e5,
    -5.206_739_091_805_716e5,
    -1.341_856_057_221_878_7e6,
    -1.846_386_717_677_034_2e6,
    -1.175_868_406_773_361_1e6,
    -2.522_154_908_110_599e5,
    -4.872_688_929_824_555e3,
];
pub(crate) const LB_DEN: [f64; 11] = [
    1.0,
    6.863_784_863_799_798e1,
    1.909_250_206_850_094_2e3,
    2.805_328_944_819_167e4,
    2.380_856_748_540_987_2e5,
    1.200_031_850_254_673_7e6,
    3.561_752_656_732_303_6e6,
    5.970_509_723_706_607e6,
    5.184_315_308_125_339e6,
    1.967_424_900_597_715_8e6,
    2.185_712_470_796_374_5e5,
];

/// Horner on ascending-power coefficients (iterate in reverse).
#[inline]
fn horner(coeffs: &[f64], x: f64) -> f64 {
    coeffs.iter().rev().fold(0.0, |acc, &c| acc * x + c)
}

/// erfc(x) for x ≥ 0 — the core piecewise computation.
fn erfc_pos(x: f64) -> f64 {
    if x < T_TINY {
        // erfc(x) = 1 − x + O(x³); the cubic term is < ½ ulp(1), so 1−x
        // is correctly rounded here.
        return 1.0 - x;
    }
    if x < 0.25 {
        let xr = x * horner(&ERF_R, x * x);
        return 1.0 - (x + xr);
    }
    if x < T_SMALL {
        let xr = x * horner(&ERF_R, x * x);
        // (x − 0.5) is Sterbenz-exact for x ∈ [0.25, 0.84375); this split
        // form avoids the cancellation of `1 − (x + xr)` near x ≈ 0.5.
        return 0.5 - ((x - 0.5) + xr);
    }
    if x < T_MID {
        let s = x - 1.0;
        return horner(&ERFC1_NUM, s) / horner(&ERFC1_DEN, s);
    }
    if x <= XMAX {
        // z-trick: z = x with the low 32 bits cleared, so z² + 0.5625 is
        // exactly representable (z has ≤ 21 significant bits) and the
        // first exp argument carries no rounding error; the residual
        // (z−x)(z+x) is tiny and goes into the second exp with the L
        // correction.
        let z = f64::from_bits(x.to_bits() & 0xFFFF_FFFF_0000_0000);
        let u = 1.0 / (x * x);
        let l = if x < T_SPLIT {
            horner(&LA_NUM, u) / horner(&LA_DEN, u)
        } else {
            horner(&LB_NUM, u) / horner(&LB_DEN, u)
        };
        let e1 = crate::kernels::exp::exp_f64(-(z * z) - 0.5625);
        let e2 = crate::kernels::exp::exp_f64((z - x) * (z + x) + l);
        return e1 * e2 / x;
    }
    0.0
}

/// Std-free `f64` error function, `no_std`. ≤ 1 ulp (see module docs).
#[inline]
pub fn erf_f64(x: f64) -> f64 {
    if x.is_nan() {
        return f64::NAN;
    }
    if x.is_infinite() {
        return if x > 0.0 { 1.0 } else { -1.0 };
    }
    let ax = if x < 0.0 { -x } else { x };
    if ax < T_SMALL {
        // erf(x) = x + x·R(x²); R(0) = 2/√π − 1 so this is exact at 0.
        return x + x * horner(&ERF_R, x * x);
    }
    let y = 1.0 - erfc_pos(ax);
    if x < 0.0 { -y } else { y }
}

/// Std-free `f64` complementary error function, `no_std`. ≤ 3 ulp.
#[inline]
pub fn erfc_f64(x: f64) -> f64 {
    if x.is_nan() {
        return f64::NAN;
    }
    if x.is_infinite() {
        return if x > 0.0 { 0.0 } else { 2.0 };
    }
    let ax = if x < 0.0 { -x } else { x };
    let c = erfc_pos(ax);
    if x < 0.0 { 2.0 - c } else { c }
}

/// Std-free `f32` error function: widen to f64, round once (perfectly
/// rounded — f32-native arithmetic cancels; see module docs).
#[inline]
pub fn erf(x: f32) -> f32 {
    erf_f64(f64::from(x)) as f32
}

/// Std-free `f32` complementary error function: widen to f64, round once.
#[inline]
pub fn erfc(x: f32) -> f32 {
    erfc_f64(f64::from(x)) as f32
}

#[cfg(test)]
mod tests {
    use super::*;

    // (x, erf(x), erfc(x)) for x ≥ 0, correctly rounded from mpmath dps=80.
    // Generated by scripts/gen_erf_reference.py — the same table the
    // integration-level accuracy tests use.
    include!("erf_reference.rs");

    /// ULP distance between two f64 (sign-magnitude aware; NaN == NaN is 0).
    fn ulps(a: f64, b: f64) -> u64 {
        if a.is_nan() && b.is_nan() {
            return 0;
        }
        if a.is_nan() || b.is_nan() {
            return u64::MAX;
        }
        let ia = a.to_bits() as i64;
        let ib = b.to_bits() as i64;
        let ia = if ia < 0 { i64::MIN - ia } else { ia };
        let ib = if ib < 0 { i64::MIN - ib } else { ib };
        (ia - ib).unsigned_abs()
    }

    #[test]
    fn erf_f64_within_1_ulp() {
        for &(x, want, _) in REF {
            let got = erf_f64(x);
            assert!(
                ulps(got, want) <= 1,
                "erf_f64({x}) = {got} want {want} ({} ulps)",
                ulps(got, want)
            );
            if x > 0.0 {
                let got_neg = erf_f64(-x);
                assert!(
                    ulps(got_neg, -want) <= 1,
                    "erf_f64({}) = {got_neg} want {}",
                    -x,
                    -want
                );
            }
        }
    }

    #[test]
    fn erfc_f64_within_3_ulp() {
        for &(x, _, want) in REF {
            let got = erfc_f64(x);
            assert!(
                ulps(got, want) <= 3,
                "erfc_f64({x}) = {got} want {want} ({} ulps)",
                ulps(got, want)
            );
            if x > 0.0 {
                let got_neg = erfc_f64(-x);
                assert!(
                    ulps(got_neg, 2.0 - want) <= 3,
                    "erfc_f64(-{x}) = {got_neg} want {}",
                    2.0 - want
                );
            }
        }
    }

    #[test]
    fn specials() {
        assert_eq!(erf_f64(0.0), 0.0);
        assert_eq!(erfc_f64(0.0), 1.0);
        assert_eq!(erf_f64(f64::INFINITY), 1.0);
        assert_eq!(erf_f64(f64::NEG_INFINITY), -1.0);
        assert_eq!(erfc_f64(f64::INFINITY), 0.0);
        assert_eq!(erfc_f64(f64::NEG_INFINITY), 2.0);
        assert!(erf_f64(f64::NAN).is_nan());
        assert!(erfc_f64(f64::NAN).is_nan());
        assert_eq!(erf_f64(100.0), 1.0);
        assert_eq!(erfc_f64(100.0), 0.0);
        assert_eq!(erfc_f64(-100.0), 2.0);
        // signed zero
        assert_eq!(erf_f64(-0.0).to_bits(), (-0.0_f64).to_bits());
        assert_eq!(erfc_f64(-0.0), 1.0);
    }

    #[test]
    fn f32_widen_matches_oracle() {
        // REF32 holds f32-representable points with the oracle rounded
        // mpf → f64 → f32 — the same single rounding the kernels apply.
        // The accuracy investigation measured 0 ulp over the full
        // 891,117-point f32 grid, so the contract is exact equality.
        for &(x, we, wc) in REF32 {
            let ge = erf(x);
            let gc = erfc(x);
            assert_eq!(ge, we, "erf({x}) = {ge} want {we}");
            assert_eq!(gc, wc, "erfc({x}) = {gc} want {wc}");
            if x > 0.0 {
                // Negation commutes with rounding → symmetry is exact.
                assert_eq!(erf(-x), -ge, "erf({}) symmetry", -x);
                // The 2−x complement does NOT commute with f32 rounding,
                // so erfc(−x) and 2−erfc(x) may differ by 1 ulp. REF32
                // only stores x ≥ 0; allow that single rounding ulp.
                let gc_neg = erfc(-x);
                let comp = 2.0 - gc;
                let u = (gc_neg.to_bits() as i64 - comp.to_bits() as i64).unsigned_abs();
                assert!(u <= 1, "erfc({}) = {gc_neg} want {comp} ({u} ulps)", -x);
            }
        }
    }

    #[test]
    fn symmetry_and_complement() {
        for &(x, _, _) in REF {
            if x > 0.0 {
                assert_eq!(erf_f64(-x), -erf_f64(x));
                // erf is computed AS 1 − erfc beyond 0.84375 → exact complement
                if x >= T_SMALL {
                    assert_eq!(erf_f64(x), 1.0 - erfc_f64(x));
                }
            }
        }
    }
}
