#!/usr/bin/env python3
"""Generate tests/erf_reference.rs: an mpmath dps=80 oracle table.

Points: specials, every region boundary +-2 ulps, investigation worst
cases, a geometric sweep 2^-20..33 (2^(1/3) steps), and a uniform sweep
0..28 step 0.1. Values are correctly rounded to f64 and emitted as hex
bit patterns so the Rust table is exact.

Requires mpmath (generation-time only — not a crate dependency):
    python3 scripts/gen_erf_reference.py > tests/erf_reference.rs
"""
import struct

import mpmath as mp

mp.mp.dps = 80

points = {0.0, 2.0**-56, 2.0**-28, 1e-300, 2.0**-1074, 1e-8, 0.00056}
# region boundaries +- 2 ulps
for b in [0.25, 0.84375, 1.25, 1 / 0.35, 4.5, 6.0, 26.5, 27.23]:
    bb = struct.unpack("<Q", struct.pack("<d", b))[0]
    for d in (-2, -1, 0, 1, 2):
        points.add(struct.unpack("<d", struct.pack("<Q", bb + d))[0])
# worst cases measured during the accuracy investigation
points.update(
    [
        0.42763,
        0.4487,
        0.81459,
        0.83258,
        1.32216,
        1.88468,
        8.16305,
        16.77781,
        9.157094,
        2.04099,
        1.25265,
    ]
)
# geometric sweep 2^-20 .. 33
x = 2.0**-20
while x < 33.0:
    points.add(x)
    x *= 1.2599210498948732  # 2^(1/3)
# uniform sweep
points.update(i * 0.1 for i in range(281))

xs = sorted(p for p in points if p >= 0 and p == p and p != float("inf"))


def bits(v):
    return struct.unpack("<Q", struct.pack("<d", v))[0]


print("//! Generated by scripts/gen_erf_reference.py — do not edit.")
print("//! (x, erf(x), erfc(x)) for x >= 0, correctly rounded from mpmath dps=80.")
print("const REF: &[(f64, f64, f64)] = &[")
for x in xs:
    xm = mp.mpf(x)
    print(
        f"    (f64::from_bits(0x{bits(x):016X}), "
        f"f64::from_bits(0x{bits(float(mp.erf(xm))):016X}), "
        f"f64::from_bits(0x{bits(float(mp.erfc(xm))):016X})),"
    )
print("];")
