#!/usr/bin/env python3
"""Generate src/kernels/erf_reference.rs: an mpmath dps=80 oracle table.

Points: specials, every region boundary +-2 ulps, investigation worst
cases, a geometric sweep 2^-20..33 (2^(1/3) steps), and a uniform sweep
0..28 step 0.1. Values are correctly rounded to f64 and emitted as hex
bit patterns so the Rust table is exact.

Requires mpmath (generation-time only — not a crate dependency):
    python3 scripts/gen_erf_reference.py > src/kernels/erf_reference.rs
"""
import struct

import mpmath as mp

mp.mp.dps = 80

points = {0.0, 2.0**-56, 2.0**-28, 1e-300, 2.0**-1074, 1e-8, 0.00056}
# region boundaries +- 2 ulps
for b in [0.25, 0.84375, 1.25, 1 / 0.35, 4.5, 6.0, 26.5, 27.23]:
    bb = struct.unpack("<Q", struct.pack("<d", b))[0]
    for d in (-2, -1, 0, 1, 2):
        points.add(struct.unpack("<d", struct.pack("<Q", bb + d))[0])
# worst cases measured during the accuracy investigation
points.update(
    [
        0.42763,
        0.4487,
        0.81459,
        0.83258,
        1.32216,
        1.88468,
        8.16305,
        16.77781,
        9.157094,
        2.04099,
        1.25265,
    ]
)
# geometric sweep 2^-20 .. 33
x = 2.0**-20
while x < 33.0:
    points.add(x)
    x *= 1.2599210498948732  # 2^(1/3)
# uniform sweep
points.update(i * 0.1 for i in range(281))

xs = sorted(p for p in points if p >= 0 and p == p and p != float("inf"))


def bits(v):
    return struct.unpack("<Q", struct.pack("<d", v))[0]


print("// Generated by scripts/gen_erf_reference.py — do not edit.")
print("// (x, erf(x), erfc(x)) for x >= 0, correctly rounded from mpmath dps=80.")
def hex64(v):
    h = f"{bits(v):016X}"
    return "_".join(h[i : i + 4] for i in range(0, 16, 4))


def hex32(v):
    h = f"{v:08X}"
    return "_".join(h[i : i + 4] for i in range(0, 8, 4))


print("const REF: &[(f64, f64, f64)] = &[")
for x in xs:
    xm = mp.mpf(float(x))
    print(
        f"    (f64::from_bits(0x{hex64(x)}), "
        f"f64::from_bits(0x{hex64(float(mp.erf(xm)))}), "
        f"f64::from_bits(0x{hex64(float(mp.erfc(xm)))})),"
    )
print("];")

# --- f32 table: oracle values at f32-representable points.
# Rounded mpf → f64 → f32 (the same single f64→f32 rounding the kernels
# apply; the accuracy investigation measured 0 ulp for this pipeline over
# the full 891,117-point f32 grid).
import numpy as np


def f32bits(v):
    return struct.unpack("<I", struct.pack("<f", v))[0]


f32pts = set()
for b in [0.25, 0.84375, 1.25, 1 / 0.35, 4.5, 6.0, 26.5, 27.23]:
    bb = struct.unpack("<I", struct.pack("<f", float(b)))[0]
    for d in (-4, -3, -2, -1, 0, 1, 2, 3, 4):
        f32pts.add(struct.unpack("<f", struct.pack("<I", bb + d))[0])
# investigation worst cases, snapped to f32
for w in [0.5, 0.83258, 1.32216, 9.157094, 9.158986]:
    f32pts.add(float(struct.unpack("<f", struct.pack("<f", w))[0]))
# geometric sweep over the f32 domain
x = 2.0**-20
while x < 28.0:
    f32pts.add(float(struct.unpack("<f", struct.pack("<f", x))[0]))
    x *= 1.0218971486541166  # 2^(1/32)
# uniform sweep
for i in range(281):
    f32pts.add(float(struct.unpack("<f", struct.pack("<f", i * 0.1))[0]))

xs32 = sorted(p for p in f32pts if p >= 0 and p == p and p != float("inf"))
print()
print("// f32-representable points; oracle rounded mpf -> f64 -> f32.")
print("const REF32: &[(f32, f32, f32)] = &[")
for x in xs32:
    xm = mp.mpf(float(x))
    e32 = float(np.float32(float(mp.erf(xm))))
    c32 = float(np.float32(float(mp.erfc(xm))))
    print(
        f"    (f32::from_bits(0x{hex32(f32bits(x))}), "
        f"f32::from_bits(0x{hex32(f32bits(e32))}), "
        f"f32::from_bits(0x{hex32(f32bits(c32))})),"
    )
print("];")
